pipeline {

    agent any

    stages {

        stage('Verify Checkout') {
            steps {
                sh '''
                    echo "===== NMS CINEMAS CI/CD ====="
                    echo "Repository:"
                    pwd
                    ls -la
                '''
            }
        }

        stage('Build Backend') {
            steps {
                sh '''
                    cd backend

                    export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
                    export PATH=$JAVA_HOME/bin:$PATH

                    export MAVEN_OPTS="-Xms128m -Xmx384m"

                    echo "===== JAVA ====="
                    java -version

                    echo "===== MAVEN ====="
                    ./mvnw --version

                    echo "===== BUILDING BACKEND ====="
                    ./mvnw clean package -DskipTests
                '''
            }
        }

        stage('Build Backend Docker Image') {
            steps {
                sh '''
                    cd backend

                    echo "===== DOCKER VERSION ====="
                    docker --version

                    echo "===== BUILDING BACKEND IMAGE ====="
                    docker build -t nms-cinemas-backend:latest .
                '''
            }
        }

    }
}
