pipeline {

    agent any

    stages {

        stage('Verify Checkout') {
            steps {
                sh '''
                    echo "===== NMS CINEMAS CI/CD ====="
                    echo "Current directory:"
                    pwd

                    echo ""
                    echo "Repository contents:"
                    ls -la

                    echo ""
                    echo "Backend:"
                    ls -la backend

                    echo ""
                    echo "Frontend:"
                    ls -la frontend
                '''
            }
        }

    }
}
